import { createContext } from "react";

export const TestContext=createContext();
export const NotificationContext = createContext();
export const UpdateRequisitionContext=createContext();
export const EmployeeLoginContext=createContext();

export const GetAllEmployeeContext=createContext();
export const GetAllRequisitionContext=createContext();


export const GetApprovalDataContext=createContext();